name: Publish bundles to Massdriver

on:
  push:
    branches:
      - main

jobs:
  publish_to_massdriver:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Massdriver CLI
        uses: dsaltares/fetch-gh-release-asset@0.0.8
        with:
          repo: "massdriver-cloud/massdriver-cli"
          file: "^mass-.*-linux-amd64\\.tar\\.gz$"
          regex: true
          token: ${{ secrets.ORGANIZATION_GITHUB_TOKEN }}

      - name: Build and Publish
        run: export PATH=$PWD:$PATH && cd definitions/artifacts && for artifact in *; do echo ${artifact}; mass schema dereference -s ${artifact} | mass definition publish -f -; done
        env:
          MASSDRIVER_API_KEY: ${{ secrets.MASSDRIVER_API_KEY }}
